alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: kissena-synergy-frontend
      match:
        path:
          prefix: /
name: kissena-synergy-website
region: sfo
static_sites:
  - catchall_document: index.html
    environment_slug: node-js
    github:
      branch: henry
      deploy_on_push: true
      repo: arklian/kissena-synergy
    name: kissena-synergy-frontend
    source_dir: frontend
