import { Request, Response } from "express";

const sample = [
    {
        id: "1",
        title: "Tech Conference 2025",
        location: "San Francisco, CA",
        description: "Join us for a day of technology insights and networking.",
        date: "01/23/2025",
        startTime: "01/23/2025, 09:00:00 AM",
        endTime: "01/23/2025, 05:00:00 PM",
        team: "green",
        partner: "Innovators Corp",
        learnMoreUrl: "https://techconference2025.com"
    },
    {
        id: "2",
        title: "Product Launch Event",
        location: "New York, NY",
        description: "Be the first to experience our latest product.",
        date: "01/22/2025",
        startTime: "01/22/2025, 10:00:00 AM",
        endTime: "01/22/2025, 12:00:00 PM",
        team: "orange",
        partner: "TechWorks Ltd",
        learnMoreUrl: "https://productlaunch2025.com"
    },
    {
        id: "3",
        title: "AI Innovation Summit",
        location: "Austin, TX",
        description: "A summit for all things Artificial Intelligence.",
        date: "01/21/2025",
        startTime: "01/21/2025, 08:00:00 AM",
        endTime: "01/21/2025, 06:00:00 PM",
        team: "blue",
        partner: "FutureTech Group",
    },
    {
        id: "4",
        title: "Health and Wellness Expo",
        location: "Los Angeles, CA",
        description: "Explore the latest trends in health and wellness.",
        date: "01/19/2025",
        startTime: "01/19/2025, 09:00:00 AM",
        endTime: "01/19/2025, 04:00:00 PM",
        team: "partner",
        partner: "Wellness Co.",
    },
    {
        id: "5",
        title: "Annual Charity Gala",
        location: "Chicago, IL",
        description: "A night to support our community initiatives.",
        date: "01/24/2025",
        startTime: "01/24/2025, 06:00:00 PM",
        endTime: "01/24/2025, 11:00:00 PM",
        team: "green",
        partner: "GiveBack Foundation",
        learnMoreUrl: "https://charitygala2025.com"
    },
    {
        id: "6",
        title: "Blockchain Developer Meetup",
        location: "Seattle, WA",
        description: "A gathering for blockchain developers and enthusiasts.",
        date: "01/20/2025",
        startTime: "",
        endTime: "",
        team: "orange",
        partner: "BlockChainInc",
        learnMoreUrl: "https://blockchainmeetup2025.com"
    },
    {
        id: "7",
        title: "Global Business Forum",
        location: "London, UK",
        description: "Leading figures discuss global business trends.",
        date: "01/22/2025",
        startTime: "01/22/2025, 08:30:00 AM",
        endTime: "01/22/2025, 05:00:00 PM",
        team: "blue",
        partner: "Global Trade Network",
        learnMoreUrl: "https://globalbusiness2025.com"
    },
    {
        id: "8",
        title: "E-Commerce Summit",
        location: "Miami, FL",
        description: "Innovators share strategies to dominate the e-commerce market.",
        date: "01/21/2025",
        startTime: "01/21/2025, 09:00:00 AM",
        endTime: "01/21/2025, 03:00:00 PM",
        team: "partner",
        partner: "ShopSmart Inc.",
    },
    {
        id: "9",
        title: "Sustainability Forum",
        location: "Denver, CO",
        description: "Join us to discuss the future of sustainable practices.",
        date: "01/25/2025",
        startTime: "01/25/2025, 10:00:00 AM",
        endTime: "01/25/2025, 04:00:00 PM",
        team: "green",
        partner: "EcoSolutions",
        learnMoreUrl: "https://sustainabilityforum2025.com"
    },
    {
        id: "10",
        title: "Digital Marketing Conference",
        location: "Boston, MA",
        description: "Learn the latest trends in digital marketing strategies.",
        date: "01/24/2025",
        startTime: "01/24/2025, 08:30:00 AM",
        endTime: "01/24/2025, 05:00:00 PM",
        team: "blue",
        partner: "Digital Pro",
        learnMoreUrl: "https://digitalmarketingconference2025.com"
    },
    {
        id: "11",
        title: "Financial Investment Forum",
        location: "Toronto, Canada",
        description: "Experts discuss investment strategies for 2025.",
        date: "01/21/2025",
        startTime: "01/21/2025, 09:30:00 AM",
        endTime: "01/21/2025, 03:30:00 PM",
        team: "orange",
        partner: "Wealth Management Group",
    },
    {
        id: "12",
        title: "Creative Arts Exhibition",
        location: "Paris, France",
        description: "An exhibition showcasing contemporary art and design.",
        date: "01/19/2025",
        startTime: "01/19/2025, 11:00:00 AM",
        endTime: "01/19/2025, 06:00:00 PM",
        team: "green",
        partner: "Creative Arts Collective",
        learnMoreUrl: "https://creativearts2025.com"
    },
    {
        id: "13",
        title: "Startup Pitch Night",
        location: "Vancouver, Canada",
        description: "Up-and-coming startups pitch to investors.",
        date: "01/18/2025",
        startTime: "01/18/2025, 06:00:00 PM",
        endTime: "01/18/2025, 09:00:00 PM",
        team: "blue",
        partner: "Investor Network",
        learnMoreUrl: "https://startuppitch2025.com"
    },
    {
        id: "14",
        title: "Healthcare Summit",
        location: "Washington, D.C.",
        description: "Discussions on the future of healthcare innovation.",
        date: "01/20/2025",
        startTime: "01/20/2025, 08:00:00 AM",
        endTime: "01/20/2025, 05:00:00 PM",
        team: "partner",
        partner: "HealthTech Innovators",
        learnMoreUrl: "https://healthcare2025.com"
    },
    {
        id: "15",
        title: "Virtual Reality Expo",
        location: "San Jose, CA",
        description: "Explore the latest advancements in virtual reality technology.",
        date: "01/19/2025",
        startTime: "01/19/2025, 09:00:00 AM",
        endTime: "01/19/2025, 06:00:00 PM",
        team: "green",
        partner: "RealityX Tech",
        learnMoreUrl: "https://vrexpo2025.com"
    },
    {
        id: "16",
        title: "International Travel Expo",
        location: "Madrid, Spain",
        description: "Discover new travel destinations and services.",
        date: "01/22/2025",
        startTime: "",
        endTime: "",
        team: "partner",
        partner: "ExploreTheWorld",
    },
    {
        id: "17",
        title: "Photography Workshop",
        location: "New York, NY",
        description: "A hands-on workshop with top photographers.",
        date: "01/20/2025",
        startTime: "01/20/2025, 10:00:00 AM",
        endTime: "01/20/2025, 03:00:00 PM",
        team: "blue",
        partner: "ShutterPro",
        learnMoreUrl: "https://photographyworkshop2025.com"
    },
    {
        id: "18",
        title: "Tech Career Fair",
        location: "Dallas, TX",
        description: "Meet top tech companies and find your next opportunity.",
        date: "01/25/2025",
        startTime: "01/25/2025, 11:00:00 AM",
        endTime: "01/25/2025, 03:00:00 PM",
        team: "partner",
        partner: "TechJobs Network",
    },
    {
        id: "19",
        title: "Digital Art Symposium",
        location: "Berlin, Germany",
        description: "Learn from digital artists around the world.",
        date: "01/23/2025",
        startTime: "01/23/2025, 09:00:00 AM",
        endTime: "01/23/2025, 04:00:00 PM",
        team: "orange",
        partner: "ArtTech Studios",
        learnMoreUrl: "https://digitalartsymposium2025.com"
    },
    {
        id: "20",
        title: "Cybersecurity Workshop",
        location: "Toronto, Canada",
        description: "Experts share tips on securing your digital presence.",
        date: "01/25/2025",
        startTime: "01/25/2025, 09:00:00 AM",
        endTime: "01/25/2025, 12:00:00 PM",
        team: "green",
        partner: "SecureTech Solutions",
        learnMoreUrl: "https://cybersecurityworkshop2025.com"
    }
];


// Used for GET: /events/{entryCount}/{offset}/{startDate}/{endDate}?
export function getEvents(req: Request, res: Response) {
  console.log(req.params);
  res.send(sample);
}
